# Generated by Django 4.2.3 on 2023-07-19 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypePlanete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVaisseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vol', models.DateField()),
                ('planete_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='solaris_app.planete')),
                ('planete_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='solaris_app.planete')),
                ('type_vaisseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaris_app.typevaisseau')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaris_app.vol')),
            ],
        ),
        migrations.AddField(
            model_name='planete',
            name='type_planete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaris_app.typeplanete'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('planete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaris_app.planete')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitePlanete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('planete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solaris_app.planete')),
            ],
        ),
    ]
