# Generated by Django 4.2.3 on 2023-07-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solaris_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
        migrations.AddField(
            model_name='vol',
            name='duree_vol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activiteplanete',
            name='planete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solaris_app.planete'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='planete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solaris_app.planete'),
        ),
        migrations.AlterField(
            model_name='planete',
            name='type_planete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solaris_app.typeplanete'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solaris_app.vol'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='planete_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vols_arrivee', to='solaris_app.planete'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='planete_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vols_depart', to='solaris_app.planete'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='type_vaisseau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solaris_app.typevaisseau'),
        ),
    ]
