# Generated by Django 4.2.3 on 2023-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0002_remove_reservation_date_reservation_vol_duree_vol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='theme',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
