# Generated by Django 4.2.3 on 2023-07-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0003_hotel_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='typevaisseau',
            name='autonomie',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typevaisseau',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typevaisseau',
            name='nbr_equipage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typevaisseau',
            name='nbr_passager_max',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typevaisseau',
            name='vitesse',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
